[package]
name = "otpqr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
colored = "2"
google-authenticator = { version = "0.3.0", features = ["with-qrcode"], default-features = false }


