FROM registry.scontain.com:5050/matteus/review:golang-1.17.6-bullseye-experimental AS builder

RUN  git clone https://github.com/sigstore/cosign \
&&  cd cosign \
&& go install ./cmd/cosign \
&& $(go env GOPATH)/bin/cosign

WORKDIR /root

CMD ["/go/bin/cosign"]

